### ISSUE TITLE
Ability to set additional arguments to app

### ISSUE THREAD

**Issue by Ivshti** [luigiplr/node-startup-manager#4]
Besides appPath, we should be able to set appArgs too

**Comment by luigiplr** [comment]
Great idea! Ill add it sometime this week.

**Comment by Ivshti** [comment]
Cheers for the christmas hat

**Comment by luigiplr** [comment]
> Cheers for the christmas hat

:+1:

**Comment by luigiplr** [comment]
@Ivshti alright added support for every OS besides OSX, please review read me/tests as the api changed.

I'll push OSX shortly.

**Comment by jaruba** [comment]
![jins-meme-smartglasses](https://cloud.githubusercontent.com/assets/1777923/11860111/e515bc84-a479-11e5-9b08-0071b52115c6.jpg)

**Comment by luigiplr** [comment]
![](http://ak-hdl.buzzfed.com/static/2015-02/21/19/imagebuzz/webdr08/anigif_optimized-6908-1424564907-19.gif)

**Comment by jaruba** [comment]
http://content.jwplatform.com/previews/lWu0YpZE-ERPbx32c

**Comment by Ivshti** [comment]
Thanks, I'll check it out

off-topic
![margery](http://img.pandawhale.com/post-40222-Natalie-Dormer-biting-apple-gi-F6Im.gif)

**Comment by luigiplr** [comment]
@Ivshti ![](https://s-media-cache-ak0.pinimg.com/736x/8e/fc/c9/8efcc92d58a6bb19188ad70751a99d5f.jpg)

**Comment by Ivshti** [comment]
did you push OS X @luigiplr 
if so, good job, you're a robot (if it works hahah)

**Comment by luigiplr** [comment]
haha @Ivshti I did indeed.
