### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Ivshti** [luigiplr/node-startup-manager#5]
```
> node-startup-manager@0.0.8 build /private/tmp/Stremio/stremio/node_modules/node-startup-manager
> rimraf build && babel lib --presets es2015 --out-dir build

sh: babel: command not found

```

**Comment by luigiplr** [comment]
What platform is this?

**Comment by Ivshti** [comment]
Mac. Shouldn't babel be in dev dependencies?

**Comment by luigiplr** [comment]
it is: `"babel-cli": "^6.3.17",`

Just did a test on Windows and its working, ill build on Mac now.

**Comment by luigiplr** [comment]
@Ivshti Just did a build on my mac and: 

![](https://i.imgur.com/FOFybg5.png)

It would appear everything went as planned? 

Could you supply some additional info as to what version of osx/node your running?

I did re-publish just in case something went astray though.

**Comment by Ivshti** [comment]
```
Ivos-iMac:tmp ivogeorgiev$ node --version
v0.12.2
Ivos-iMac:tmp ivogeorgiev$ # OS X Yosemite
Ivos-iMac:tmp ivogeorgiev$ npm install node-startup-manager
/
> node-startup-manager@0.0.9 postinstall /private/tmp/node_modules/node-startup-manager
> npm run build


> node-startup-manager@0.0.9 build /private/tmp/node_modules/node-startup-manager
> rimraf build && babel lib --presets es2015 --out-dir build

sh: rimraf: command not found

```

Different error now.
You probably have rimraf and babel installed globally

Ignore the OS X/node versions, they don't matter.
What matters is having rimraf/babel installed. I think you'd have to put them into the regular dependencies :( 

Can we just get rid of them somehow? Or just add them to deps

**Comment by luigiplr** [comment]
Hmm very strange indeed, I removed the rimraf dep all together in latest commit/version hopefully it fixes the issues :)

**Comment by luigiplr** [comment]
@Ivshti is it fixed for you?

**Comment by Ivshti** [comment]
@luigiplr YES! It works. You're awesome

**Comment by luigiplr** [comment]
Sweet! and thanks :D
