### ISSUE TITLE
Can we get rid of ES6 dependance?

### ISSUE THREAD

**Issue by Ivshti** [luigiplr/node-startup-manager#6]
I'm thinking of reverting stremio to electron 0.29 and this breaks this module for me.

If @luigiplr gives me the permission I'm changing to to not depend on ES6

There's no real rational reason for it

**Comment by luigiplr** [comment]
Added you as a collaborator.

Feel free to push right to the repo!

**Comment by Ivshti** [comment]
I'm stupid. Latest version works fine. Since it builds to JS.
